## Fibonacci series

In [11]:
n=int(input('Enter the desired length of series'))

a=1
b=1
print(a)
print(b)

for i in range(1,n-1):
    c=a+b
    print (c)
    b=a
    a=c
    

Enter the desired length of series10
1
1
2
3
5
8
13
21
34
55


## Write a program to calculate the sum of series up to n term. For example, if n =5 the series will become 2 + 22 + 222 + 2222 + 22222 = 24690

In [19]:
n=int(input('Enter the number of terms'))

print(f'{n} is the number entered')
a=2
sum=0

for i in range (1,n+1):
    sum+=a
    a=a*10+2
    
print(sum)
    


Enter the number of terms5
5 is the number entered
24690


## Create a 4X2 integer array and Prints its attributes


In [34]:
import numpy as np
import pandas as pd

a = np.empty([4,2],dtype=np.uint16)
print(a)

print('Array shape:', np.shape(a))

print('Array dimensions: ',a.ndim)

print('Array size: ', a.itemsize)

[[  176 64429]
 [ 4787 36447]
 [59082 11758]
 [24635  1890]]
Array shape: (4, 2)
Array dimensions:  2
Array size:  2


## Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [37]:
import numpy as np

a=np.arange(100,200,10)
b=a.reshape(5,2)  #reshape array has to be saved into a variable
print(b)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


## Following is the provided numPy array. Return array of items by taking the third column from all rows

In [50]:
import numpy as np

a=np.arange(50,150,5)
b=a.reshape(5,4)
print('\nSample array is: \n',b)

c=b[:,2]

print('\n Extracted array is: ')
print(c)


Sample array is: 
 [[ 50  55  60  65]
 [ 70  75  80  85]
 [ 90  95 100 105]
 [110 115 120 125]
 [130 135 140 145]]

 Extracted array is: 
[ 60  80 100 120 140]
